-- MySQL Script generated by MySQL Workbench
-- Fri Dec  9 21:47:28 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema isHickeyGood
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema isHickeyGood
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `isHickeyGood` DEFAULT CHARACTER SET utf8 ;
USE `isHickeyGood` ;

-- -----------------------------------------------------
-- Table `isHickeyGood`.`ratings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `isHickeyGood`.`ratings` (
  `rating_id` INT NOT NULL AUTO_INCREMENT,
  `user_rating` VARCHAR(45) BINARY NULL,
  `rating_time` TIMESTAMP(2) NULL,
  PRIMARY KEY (`rating_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
